default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: CoderTicket_development

test:
  <<: *default
  database: CoderTicket_test

production:
  <<: *default
  database: CoderTicket_production
  username: CoderTicket
  password: <%= ENV['CODERTCKET_DATABASE_PASSWORD'] %>
